spring:
  application:
    name: file-service
  profiles:
    active: prod
  config:
    import: configserver:http://config-server:8888
  cloud:
    kubernetes:
      discovery:
        enabled: true
      config:
        enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    appname: FILE-SERVICE
    preferIpAddress: true
logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.config: DEBUG
    org.springframework.cloud.config.server: DEBUG
    org.springframework.boot.context.logging: DEBUG

