spring:
  application:
    name: file-service
  profiles:
    active: prod
  config:
    import: optional:configserver:http://config-server:8888

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.cloud.config: DEBUG
    org.springframework.cloud.config.server: DEBUG
