spring:
  application:
    name: comment-service
  profiles:
    active: prod
  config:
    import: configserver:http://config-server:8888
  cloud:
    config:
      fail-fast: true

logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.config: DEBUG
    org.springframework.cloud.config.server: DEBUG
    org.springframework.boot.context.logging: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true