spring:
  application:
    name: group-service
  profiles:
    active: prod
  config:
    import: configserver:http://config-server:8888
  cloud:
    kubernetes:
      discovery:
        enabled: true
      config:
        enabled: true
        name: group-service

    config:
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 2000
        max-attempts: 6
  # DB 설정 추가 (Config Server 연결 실패 시 fallback으로 사용)
  datasource:
    url: jdbc:mysql://mysql:3306/parandb
    username: [ USERNAME ]
    password: [ PASSWORD ]
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    appname: GROUP-SERVICE
    preferIpAddress: true

logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.config: DEBUG
    org.springframework.cloud.config.server: DEBUG
    org.springframework.boot.context.logging: DEBUG