spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    kubernetes:
      discovery:
        enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    appname: GATEWAY-SERVER
    preferIpAddress: true
logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.web: D  gEBUG
    org.springframework.cloud.config: DEBUG
    org.springframework.cloud.config.server: DEBUG
    org.springframework.boot.context.logging: DEBUG