#gateway-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server

spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-server
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: gateway-server
          image: songjih452/paran:gateway-latest
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "local"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-server:8888"
            - name: SPRING_CLOUD_CONFIG_FAIL_FAST
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-server
spec:
  selector:
    app: gateway-server
  ports:
    - port: 8000
  type: LoadBalancer
---

#chat-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: songjih452/paran:chat-latest
          imagePullPolicy: Always
          env:
            - name: SPRING_CLOUD_KUBERNETES_ENABLED
              value: "true"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-server:8888"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: SPRING_APPLICATION_NAME
              value: "chat-service"

---

# comment-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment-service
  template:
    metadata:
      labels:
        app: comment-service
    spec:

      dnsPolicy: ClusterFirst
      containers:
        - name: comment-service
          image: songjih452/paran:comment-latest
          imagePullPolicy: Always
          env:
            - name: SPRING_CLOUD_KUBERNETES_ENABLED
              value: "true"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-server:8888"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: SPRING_APPLICATION_NAME
              value: "comment-service"

---

#file-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
    spec:
      containers:
        - name: file-service
          image: songjih452/paran:file-latest
          imagePullPolicy: Always
          env:
            - name: SPRING_CLOUD_KUBERNETES_ENABLED
              value: "true"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-server:8888"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: SPRING_APPLICATION_NAME
              value: "file-service"

---

#group-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: group-service
  template:
    metadata:
      labels:
        app: group-service
    spec:
      containers:
        - name: group-service
          image: songjih452/paran:group-latest
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-server:8888"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: "org.hibernate.dialect.MySQLDialect"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: mysql-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: mysql-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: mysql-password
---
apiVersion: v1
kind: Service
metadata:
  name: group-service
spec:
  selector:
    app: group-service
  ports:
    - port: 8085
      targetPort: 8085
---

#room-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-service
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room-service
  template:
    metadata:
      labels:
        app: room-service
    spec:
      containers:
        - name: room-service
          image: songjih452/paran:room-latest
          imagePullPolicy: Always
          env:
            - name: SPRING_CLOUD_KUBERNETES_ENABLED
              value: "true"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-server:8888"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: SPRING_APPLICATION_NAME
              value: "room-service"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

---

#user-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: songjih452/paran:user-latest
          imagePullPolicy: Always
          env:
            - name: SPRING_CLOUD_KUBERNETES_ENABLED
              value: "true"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-server:8888"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: SPRING_APPLICATION_NAME
              value: "user-service"

---
