spring:
  application:
    name: user-service
  config:
    import: configserver:http://config-server.default.svc.cluster.local:8888
  cloud:
    config:
      fail-fast: true
      retry:
        enabled: true
        initial-interval: 1000
        max-interval: 2000
        max-attempts: 6
      discovery:
        enabled: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.cloud.config: DEBUG
    org.springframework.cloud.config.server: DEBUG
    com.netflix.discovery: DEBUG