spring:
  application:
    name: chat-service
  profiles:
    active: prod
  config:
    import: "configserver:http://localhost:8888"
  cloud:
    config:
      fail-fast: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.cloud.config: DEBUG
    org.springframework.cloud.config.server: DEBUG
